/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class SquadTest {
    @Test public void Squad_instantiatesCorrectly_true() {
        Squad mySquad = new Squad("Avengers");
        assertEquals("Avengers", mySquad.getName());
      }
}
